---
name: Bug Report
description: Create a report to help us improve.
title: <Bug Report>
labels: []
body:
- type: textarea
  attributes:
    label: Describe the bug
    description: Create a report to help us improve.
