name: Bug Report
description: Create a report to help us improve.
title: "<Bug Report>"
labels: []
body:
- type: textarea
  attributes:
    label: Describe the bug
    description: 
      Create a report to help us improve.

      Thanks for stopping by to let us know something could be better!

      PLEASE READ: If you have a support contract with Google, please create an issue in the support console instead of filing on GitHub. This will ensure a timely response.

      Please run down the following list and make sure you've tried the usual "quick fixes":

      - Search the issues already opened: [GitHub Issues](https://github.com/googleapis/java-firestore/issues)
      - Check for answers on StackOverflow: [StackOverflow - Google Cloud Platform](http://stackoverflow.com/questions/tagged/google-cloud-platform)

      If you are still having issues, please include as much information as possible.

  validations:
    required: true
- type: markdown
  attributes:
    label: Environment (please complete the following information about Desktop).
    description: Environment details
    value: |
      - Specify the API at the beginning of the title. For example, "BigQuery: ...". General, Core, and Other are also allowed as types.
      - OS type and version:
      - Java version:
      - Version(s):
  validations:
    required: false  
- type: textarea
  attributes:
    label: Steps to reproduce
    value: |
        1. ?
        2. ?
  validations:
    required: false
- type: markdown
  attributes:
    value: |
        **Code example**
        ```
        // example
        ```
  validations:
    required: false
- type: markdown
  attributes:
    value: |
        **Stack trace**
        Any relevant stack trace here.
  validations:
    required: false 
- type: markdown
  attributes:
    value: |
        **External references such as API reference guides**
        -
  validations:
    required: false     
- type: textarea
  attributes:
    label: Error message (if applicable)
      value: |
        Provide the complete error message you received here.
  validations:
    required: false 
- type: markdown
  attributes:
    value: |
        **Any additional information below**
        Following these steps guarantees the quickest resolution possible.

        Thanks!
  validations:
    required: false       
