---
name: Bug Report
description: Create a report to help us improve.
title: <Bug Report>
labels: []
body:
- type: textarea
  attributes:
    label: Describe the bug
    description: Create a report to help us improve.
      
- type: markdown
  attributes:
    label: Environment (please complete the following information about Desktop).
    description: Environment details
    value: >
      - Specify the API at the beginning of the title. For example, "BigQuery:
      ...". General, Core, and Other are also allowed as types.

      - OS type and version:

      - Java version:

      - Version(s):
  validations:
    required: false
